//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayin
    {
        public System.Guid id { get; set; }
        public string lingjianbh { get; set; }
        public string chanpinmc { get; set; }
        public string chexing { get; set; }
        public string shourongs { get; set; }
        public string jiantufx { get; set; }
        public byte[] jiantu { get; set; }
        public string beizhu { get; set; }
        public string rongqixh { get; set; }
        public string erweima { get; set; }
    }
}
