//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_daily_count
    {
        public System.Guid id { get; set; }
        public System.DateTime count_date { get; set; }
        public int count { get; set; }
        public string formatdt { get; set; }
    }
}
